@startuml normal_sequence

actor Me

participant Viewer
queue RequestHandlerRequest
queue RequestHandlerResponse
participant RequestHandlerManager
queue RequestHandlerQueue
participant RequestHandler
database Files

activate Me
activate Viewer
activate RequestHandlerManager
activate RequestHandlerRequest
activate RequestHandlerResponse

Me -> Viewer : 0. App, fetch me\nsome character data!

Viewer -> RequestHandlerRequest : 1. Push (data request)
RequestHandlerRequest -> RequestHandlerManager : 1.1. Pull (data request)

create RequestHandler
RequestHandlerManager -> RequestHandler : 1.1.1. Create new\ndata retrieval task
activate RequestHandler

RequestHandler -> Files : 1.1.1.1. Retrieve file
Files -> RequestHandler : 1.1.1.1. Retrieve file
RequestHandler -> RequestHandler : 1.1.1.2. Parse file and\nretrieve relevent data
RequestHandler -> RequestHandlerQueue : 1.1.1. Push (relevent data)

deactivate RequestHandler
destroy RequestHandler

RequestHandlerQueue -> RequestHandlerManager : 1.1.1. Pull (relevent data)
RequestHandlerManager -> RequestHandlerManager : 1.1.2. Link retrieved\ndata to request

RequestHandlerManager -> RequestHandlerResponse : 1.1. Push (requested data)
RequestHandlerResponse -> Viewer : 1. Pull (requested data)

Viewer -> Viewer : 2. Render data

Viewer -> Me : 0. Wow, graphics!

@enduml
